set nu
syntax on

"高亮显示搜索结果
set hlsearch
"输入时搜索
set incsearch
"设置递进搜索
set incsearch
"设置忽略搜索大小写
set ignorecase
"设置智能大小写搜索,只有搜索时输入的有大写字母，才会自动区分大小写搜索
set smartcase


"当前行高亮
set cursorline
"设置当前行高亮颜色
hi CursorLine cterm=NONE ctermbg=black ctermfg=grey guibg=NONE guifg=NONE
"设置当前列高亮
"set cursorcolumn
"设置列高亮颜色
"hi Cursorcolumn  cterm=NONE ctermbg=black ctermfg=NONE guibg=NONE guifg=NONE

"设置显示不可见字符
"set list 
"设置不可见字符 tab显示为--
"set listchars=tab:--
"按下回车键后，下一行的缩进会自动跟上一行的缩进保持一致
set autoindent

set wildmenu "命令补全

map s :w<CR>
map q :q<CR>
map Q :q!<CR>
map R :PlugInstall<CR>

call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'Valloric/YouCompleteMe', {'do': 'python3 install.py'}
call plug#end()

" NerdTree
map <F2> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" NERDTree-git
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ "Unknown"   : "?"
    \ }



