
source ~/.git-completion.bash
source ~/.git-prompt.sh

#export GIT_PS1_SHOWDIRTYSTATE=1
#export PS1='\w$(__git_ps1 " (%s)")\$'

export PS1='\[\033[0;36m\]* \w \[\033[1;34m\]$(__git_ps1)\[\033[0m\] \[\033[0;36m\]*\[\033[0m\n  `if [[ $? = '0' ]]; then echo "\[\033[1;33m\]";else echo "\[\033[0;31m\]";fi`\u→ \$ \[\033[0m\]'
